version: "3.8"

services:
  postgres:
    image: postgres:14
    environment:
      POSTGRES_DB: message_app
      POSTGRES_USER: message_app
      POSTGRES_PASSWORD: 123456
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  server:
    build: ./server
    ports:
      - "3001:3001"
    environment:
      DB_HOST: postgres
      DB_PORT: 5432
      DB_NAME: message_app
      DB_USER: message_app
      DB_PASSWORD: 123456
    depends_on:
      - postgres

  client:
    build: ./client
    ports:
      - "3000:3000"
    depends_on:
      - server

volumes:
  postgres_data:
