version: "3.8"
services:
  postgres:
    image: postgres:14
    container_name: message-postgres
    environment:
      POSTGRES_DB: message_app
      POSTGRES_USER: message_app
      POSTGRES_PASSWORD: 123456
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
